# This is a basic workflow to help you get started with Actions

name: checkmarx workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
  # Steps represent a sequence of tasks that will be executed as part of the job
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Scan Iac with kics
    - name: run kics Scan
      uses: checkmarx/kics-action@v1.0
      with:
        path: 'docker'
        output_path: 'results.json'
	
	#Display the results in json format	  
#- name: display kics results
     #run: |
       # cat results.json
 
